version: '3'

services:
  app:
    build:
      context: ./app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    volumes:
      - appdata:/app
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: hugaleno/nginx:app
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  dbdata:
  appdata: